from pydantic import BaseModel,Field
from typing import Annotated
class ChatRequest(BaseModel):
    question : Annotated[str,Field(..., description = "Write Down the question for medical assistance")]

class ChatResponse(BaseModel):
    answer : Annotated[str,Field(..., description = "Answer generated by the medical chatbot")]